routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Front\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. Thesemaster
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'front.', 'namespace' => 'Front'], function(){
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('sign-in');
    Route::post('/login', [LoginController::class, 'login'])->name('user.submit.login');
    Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('show.register');
    Route::post('/register', [RegisterController::class, 'create'])->name('register');
});

app/Models/Admin.php
<?php

namespace App\Models;

use App\Casts\Status;
use App\Facade\Uploaded;
use App\Http\Traits\AdminTrait;
use Illuminate\Support\Facades\Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes, AdminTrait;

    public $guard = 'admin';

    protected $guarded = ['id', 'password_confirmation'];

    protected $hidden = ['password', 'remember_token'];

    protected $casts = ['status' => Status::class];

    protected $with = ['role'];

    public function getImageUrlAttribute()
    {
        return Uploaded::defaultImage($this->image,'admins');
    }

    public function getFullNameAttribute()
    {
        return $this->fname . ' ' . $this->lname;
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    public function role()
    {
        return $this->belongsTo(Role::class,'role_id','id')->withDefault(['name' => trans('no-value')]);
    }

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }
}

resources/views/Back/layouts/partials/navbar.blade.php
<div class="navbar-custom">
    <ul class="list-unstyled topnav-menu float-right mb-0">
        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle mr-0 waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <img src="{{ getFlagLang() }}" alt="lang" width="30">
            </a>

            <div class="dropdown-menu dropdown-menu-right profile-dropdown">
                <a href="{{ LaravelLocalization::getLocalizedURL('en') }}" class="english dropdown-item notify-item">
                    <img src="{{ getFlagLang('gb') }}" alt="">
                    English
                </a>
                <a href="{{ LaravelLocalization::getLocalizedURL('ar') }}" class="arabic dropdown-item notify-item">
                    <img src="{{ getFlagLang('sa') }}" alt="">
                    العربية
                </a>
            </div>
        </li>

        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <img src="{{ $auth->image_url }}" alt="user-image" class="rounded-circle">
                <span class="pro-user-name ml-1">{{ ucwords($auth->name) }} <i class="mdi mdi-chevron-down"></i></span>
            </a>

            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                <a href="{{ route('admins.profile') }}" class="dropdown-item notify-item"><i class="fe-user"></i><span>@lang('back.my-account')</span></a>

                <div class="dropdown-divider"></div>

                <a href="{{ route('admin.logout') }}"
                   onclick="event.preventDefault();document.getElementById('logout-form-0').submit();" class="dropdown-item notify-item">
                    <i class="fe-log-out"></i><span>@lang('back.logout')</span>
                </a>

                <form id="logout-form-0" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>

    <div class="logo-box">
        <a href="{{ route('admin-panel') }}" class="logo text-center" style="background-color: darkgray;">
            <span class="logo-lg">
                <img src="{{ url('public/admin/images/image.png') }}" alt="" height="60">
            </span>
            <span class="logo-sm">
                <img src="{{ url('public/admin/images/image.png') }}" alt="" height="24">
            </span>
        </a>
    </div>

    <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
        <li><button class="button-menu-mobile disable-btn waves-effect"><i class="fe-menu"></i></button></li>

        <li><h4 class="page-title-main">@lang('back.dashboard')</h4></li>
    </ul>
</div>

resources/views/Back/layouts/partials/scripts.blade.php
{!! script('public/admin/js/vendor.min.js') !!}
{!! script('public/admin/libs/jquery-knob/jquery.knob.min.js') !!}
{!! script('public/admin/libs/morris-js/morris.min.js') !!}
{!! script('public/admin/libs/raphael/raphael.min.js') !!}
{!! script('public/admin/assets/js/sweetalert.min.js') !!}
{!! script('public/admin/libs/toastr/toastr.min.js') !!}
{!! script('public/admin/libs/custombox/custombox.min.js') !!}
{!! script('https://malsup.github.io/jquery.form.js') !!}

<!-- Plugins Js -->
{!! script('public/admin/libs/bootstrap-tagsinput/bootstrap-tagsinput.min.js') !!}
{!! script('public/admin/libs/switchery/switchery.min.js') !!}
{!! script('public/admin/libs/multiselect/jquery.multi-select.js') !!}
{!! script('public/admin/libs/jquery-quicksearch/jquery.quicksearch.min.js') !!}
{!! script('public/admin/libs/select2/select2.min.js') !!}
{!! script('public/admin/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js') !!}
{!! script('public/admin/libs/jquery-mask-plugin/jquery.mask.min.js') !!}
{!! script('public/admin/libs/moment/moment.js') !!}
{!! script('public/admin/libs/bootstrap-timepicker/bootstrap-timepicker.min.js') !!}
{!! script('public/admin/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.js') !!}
{!! script('public/admin/libs/bootstrap-datepicker/bootstrap-datepicker.min.js') !!}
{!! script('public/admin/libs/bootstrap-daterangepicker/daterangepicker.js') !!}
{!! script('public/admin/libs/bootstrap-maxlength/bootstrap-maxlength.min.js') !!}
{!! script('public/admin/libs/dropify/dropify.min.js') !!}
{!! script('public/admin/js/pages/form-fileupload.init.js') !!}
{!! script('public/admin/js/pages/form-advanced.init.js') !!}

{!! script('public/admin/assets/js/crud.js') !!}
{!! script('public/admin/assets/js/scripts.js') !!}
{!! script('public/admin/assets/js/lang.min.js') !!}
{!! script('public/admin/assets/js/plugins/forms/selects/bootstrap_select.min.js') !!}
{!! script('public/admin/assets/js/plugins/forms/selects/select2.min.js') !!}
{!! script('public/admin/assets/js/jquery.print.js') !!}
{!! script('public/admin/js/HoldOn.min.js') !!}
{!! script('public/admin/js/app.min.js') !!}

<script>
    let rootPath = '{{ root() }}/' + '{{ getLocale() }}/admin-panel';

    let languages = {
        "paginate": {
            "previous": "@lang('pagination.previous')",
            "next": "@lang('pagination.next')",
            "first": "@lang('datatables.first')",
            "last": "@lang('datatables.last')",
        },
        "search": "@lang('datatables.search') : ",
        "infoEmpty": "@lang('datatables.emptyshowing')",
        "info": "@lang('datatables.showResult')",
        "emptyTable": "@lang('datatables.no-data-available')",
        "infoFiltered": "@lang('datatables.infoFiltered')",
        "zeroRecords": "@lang('datatables.zeroRecords')",
        "loadingRecords": "&nbsp;",
        "processing"	: "<i class='fa fa-3x fa-asterisk fa-spin'></i>"
    };

    let swalObjectTerminated = {title: "@lang('back.a-message')", text: "@lang('back.operation-terminated')", icon: "success", button: "@lang('back.ok')"};
</script>

resources/views/Back/layouts/partials/sidebar.blade.php
<div id="sidebar-menu">
    <ul class="metismenu" id="side-menu">
        <li><a href="{{ route('admin-panel') }}"><i class="mdi mdi-view-dashboard"></i><span> @lang('back.dashboard')</span></a></li>

{{--        @if(permission_route_checker('contacts.index'))--}}
{{--            <li>--}}
{{--                <a href="{{ route('contacts.index') }}">--}}
{{--                    <i class="mdi mdi-email-open"></i>--}}
{{--                    <span>--}}
{{--                    @if($newMessagesCount)--}}
{{--                        <label class="badge badge-danger">{{ $newMessagesCount }}</label>--}}
{{--                    @endif--}}
{{--                    @lang('back.contacts.contacts')--}}
{{--                </span>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--        @endif--}}

        @foreach(models() as $model => $value)
            @if(permission_route_checker(plural($model).'.index'))
                <li>
                    <a href="{{ route(plural($model).'.index') }}">
                        <i class="mdi mdi-{{ $value['icon'] }}"></i>
                        <span> @lang('back.'.plural($model).'.'.plural($model)) </span>
                    </a>
                </li>
            @endif
        @endforeach

        @if(permission_route_checker('teams.index'))
            <li>
                <a href="{{ route('teams.index') }}">
                    <i class="mdi mdi-trophy-award"></i>
                    <span>
                    @lang('back.teams.teams')
                </span>
                </a>
            </li>
        @endif

{{--        @if(permission_route_checker('settings.index'))--}}
{{--            <li>--}}
{{--                <a href="{{ route('settings.index') }}">--}}
{{--                    <i class="mdi mdi-settings-outline"></i>--}}
{{--                    <span> @lang('back.settings.settings') </span>--}}
{{--                </a>--}}
{{--            </li>--}}
{{--        @endif--}}
    </ul>
</div>

resources/views/Back/layouts/partials/styles.blade.php
<!--Morris Chart-->
{!! style('public/admin/libs/morris-js/morris.css') !!}

<!-- Plugins css -->
{!! style('public/admin/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css') !!}
{!! style('public/admin/libs/bootstrap-colorpicker/bootstrap-colorpicker.min.css') !!}
{!! style('public/admin/libs/bootstrap-timepicker/bootstrap-timepicker.min.css') !!}
{!! style('public/admin/libs/bootstrap-datepicker/bootstrap-datepicker.css') !!}
{!! style('public/admin/libs/bootstrap-daterangepicker/daterangepicker.css') !!}
{!! style('public/admin/libs/bootstrap-tagsinput/bootstrap-tagsinput.css') !!}
{!! style('public/admin/libs/multiselect/multi-select.css') !!}
{!! style('public/admin/libs/switchery/switchery.min.css') !!}
{!! style('public/admin/libs/switchery/switchery.min.css') !!}
{!! style('public/admin/libs/custombox/custombox.min.css') !!}
{!! style('public/admin/libs/select2/select2.min.css') !!}
{!! style('public/admin/libs/dropify/dropify.min.css') !!}

<!-- Global stylesheets -->
{!! style('public/admin/css/bootstrap.min.css') !!}
{!! style('public/admin/css/icons.min.css') !!}
{!! style('public/admin/css/fontSize.css') !!}

@if(app()->isLocale('ar'))
    {!! style('public/admin/css/app-rtl.min.css') !!}
@else
    {!! style('public/admin/css/app.min.css') !!}
@endif

{!! script('public/admin/assets/js/core/libraries/jquery.min.js') !!}
{!! script('public/admin/assets/js/core/libraries/bootstrap.min.js') !!}
{!! script('public/admin/assets/js/plugins/loaders/blockui.min.js') !!}
{!! script('public/admin/assets/js/plugins/loaders/pace.min.js') !!}
{!! style('public/admin/libs/toastr/toastr.min.css') !!}
{!! script('public/admin/ckeditor/ckeditor.js') !!}
{!! style('public/admin/css/HoldOn.min.css') !!}
{!! style('https://fonts.googleapis.com/css2?family=Open+Sans&display=swap') !!}
{!! style('https://fonts.gstatic.com', ['rel' => 'preconnect']) !!}
{!! style('https://fontlibrary.org/face/droid-arabic-kufi', ['media' => 'screen']) !!}
{!! script('https://www.google.com/jsapi') !!}
<!-- /global stylesheets -->

<style>
    body, h1, h2, h3, h4, h5, h6, span, label {
        font-family: 'DroidArabicKufiRegular', serif;
    }
    .nav-tabs .nav-link.active, .nav-tabs .nav-item.show .nav-link{
        color: #eee;
        background-color: #35b8e0;
        border-color: #dee2e6 #dee2e6 #fff;
    }
    .unselectable {
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }
</style>

resources/views/Back/layouts/partials/userBox.blade.php
<div class="user-box text-center">
    <img src="{{ $auth->image_url }}" alt="user-img" title="{{ucwords($auth->name)}}" class="rounded-circle img-thumbnail avatar-lg">
    <div class="dropdown">
        <a href="javascript:void(0);" class="text-dark dropdown-toggle h5 mt-2 mb-1 d-block" data-toggle="dropdown">{{ $auth->name }}</a>
        <div class="dropdown-menu user-pro-dropdown">
            <a href="{{ route('admins.profile') }}" class="dropdown-item notify-item">
                <i class="fe-user mr-1"></i>
                <span>@lang('back.my-account')</span>
            </a>

            <a href="{{ route('admin.logout') }}" class="dropdown-item notify-item"
               onclick="event.preventDefault();document.getElementById('logout-form-1').submit();">
                <i class="fe-log-out mr-1"></i> @lang('back.logout')
            </a>

            <form id="logout-form-1" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </div>
    </div>

    <p class="text-muted">{{ $auth->role->name }}</p>
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="{{ route('settings.index') }}" class="text-muted">
                <i class="mdi mdi-settings"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{{ route('admin.logout') }}" onclick="event.preventDefault();document.getElementById('logout-form-3').submit();" class="text-custom">
                <i class="mdi mdi-power"></i>
            </a>
            <form id="logout-form-3" action="{{ route('admin.logout') }}" method="POST"
                  style="display: none;">
                @csrf
            </form>
        </li>
    </ul>
</div>