routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Front\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. Thesemaster
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['as' => 'front.', 'namespace' => 'Front'], function(){
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('sign-in');
    Route::post('/login', [LoginController::class, 'login'])->name('user.submit.login');
    Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('show.register');
    Route::post('/register', [RegisterController::class, 'create'])->name('register');
});

app/Models/Admin.php
<?php

namespace App\Models;

use App\Casts\Status;
use App\Facade\Uploaded;
use App\Http\Traits\AdminTrait;
use Illuminate\Support\Facades\Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes, AdminTrait;

    public $guard = 'admin';

    protected $guarded = ['id', 'password_confirmation'];

    protected $hidden = ['password', 'remember_token'];

    protected $casts = ['status' => Status::class];

    protected $with = ['role'];

    public function getImageUrlAttribute()
    {
        return Uploaded::defaultImage($this->image,'admins');
    }

    public function getFullNameAttribute()
    {
        return $this->fname . ' ' . $this->lname;
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    public function role()
    {
        return $this->belongsTo(Role::class,'role_id','id')->withDefault(['name' => trans('no-value')]);
    }

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }
}

app/Http/Controllers/Back/AdminController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\RepoController;
use App\Http\Requests\Back\EditAdminRequest;
use App\Http\Requests\Back\CreateAdminRequest;
use App\Repository\Contracts\IAdminRepository;
use App\Http\Requests\Back\EditAdminProfileRequest;

class AdminController extends RepoController
{
    public function __construct(IAdminRepository $repository)
    {
        parent::__construct($repository);
    }

    public function showAdminMessage($id)
    {
        return self::repo()->showAdminMessage($id);
    }

    public function sendAdminMessage(Request $request)
    {
        return self::repo()->sendAdminMessage($request);
    }

    public function AdminUpdateProfile(EditAdminProfileRequest $request)
    {
        return self::repo()->updateAdminProfile($request);
    }

    public function adminProfile()
    {
        return self::repo()->adminProfile();
    }

    public function store(CreateAdminRequest $request)
    {
        return self::repo()->store($request);
    }

    public function update(EditAdminRequest $request, Admin $admin)
    {
        return self::repo()->update($request, $admin);
    }
}

app/Http/Controllers/Back/AgeController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Age;
use App\Http\Requests\Back\EditAgeRequest;
use App\Http\Controllers\RepoController;
use App\Http\Requests\Back\CreateAgeRequest;
use App\Repository\Contracts\IAgeRepository;

class AgeController extends RepoController
{
    public function __construct(IAgeRepository $repository)
    {
        parent::__construct($repository);
    }

    public function index()
    {
        return view('Back.Ages.index', ['ages' => Age::latest()->has('sport')->paginate(10), 'search' => false]);
    }

    public function store(CreateAgeRequest $request)
    {
        return self::repo()->store($request);
    }

    public function update(EditAgeRequest $request, Age $age)
    {
        return self::repo()->update($request, $age);
    }
}

app/Http/Controllers/Back/ContactController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Contact;
use Illuminate\Http\Request;
use App\Exports\ContactsExport;
use App\Facade\Support\CrudMessage;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Controllers\Controller;
use App\Http\Requests\Back\SendUserReplayMessageRequest;

class ContactController extends Controller
{
    public function Contacts()
    {
        return view('Back.Contacts.contacts', ['contacts' => Contact::paginate(10), 'search' => false]);
    }

    public function showMessageDetails($id)
    {
        if (!$message = Contact::find($id)) return CrudMessage::fails(trans('responseMessages.product-not-exist'));

        $message->update(['is_seen' => 1]);

        return view('Back.Contacts.messageDetailsModal', compact('message'))->render();
    }

    public function show(Contact $contact)
    {
        return view('Back.Contacts.show', compact('contact'));
    }

    public function sendUserMessage($id)
    {
        if (!$message = Contact::find($id)) return CrudMessage::fails(trans('back.message-not-exists'));

        return view('Back.Contacts.sendUserMessageModal', compact('message'));
    }

    public function SendUserReplayMessage(SendUserReplayMessageRequest $request)
    {
        return Contact::sendUserReplayMessage($request);
    }

    public function ContactsExport()
    {
        return Excel::download(new ContactsExport, 'contacts.xlsx');
    }

    public function DeleteContact(Request $request)
    {
        return Contact::deleteMessage($request);
    }

    public function search(Request $request)
    {
        if(is_null($request->term)) return redirect()->route('contacts.index');

        return view('Back.Contacts.contacts', ['contacts' => Contact::search($request->term)->paginate(10), 'search' => true]);
    }
}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\User;
use App\Models\Admin;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        $data['users'] = User::latest()->get();

        $data['admins'] = Admin::where('role_id', '!=', 1)->latest()->get();

        return view('Back.index', self::setHomeDonutsCharts($data));
    }

    private static function setHomeDonutsCharts($data)
    {
        return [
            'admin' => self::getModelCount($data['admins'],'admin'),
            'user'  => self::getModelCount($data['users'],'user'),
        ];
    }

    private static function getModelCount($collection, $modelName)
    {
        $model = plural($modelName);

        return [
            'active_' . $model    => $collection->where('status', 1),
            'deductive_' . $model => $collection->where('status', 0)
        ];
    }
}

app/Http/Controllers/Back/RoleController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Role;
use App\Http\Controllers\RepoController;
use App\Http\Requests\Back\EditRoleRequest;
use App\Http\Requests\Back\CreateRoleRequest;
use App\Repository\Contracts\IRoleRepository;

class RoleController extends RepoController
{
    public function __construct(IRoleRepository $repository)
    {
        parent::__construct($repository);
    }

    public function store(CreateRoleRequest $request)
    {
        return self::repo()->store($request);
    }

    public function update(EditRoleRequest $request, Role $role)
    {
        return self::repo()->update($request, $role);
    }
}

app/Http/Controllers/Back/SettingController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SettingController extends Controller
{
    public function index()
    {
        $settings = cacheModel('setting', Setting::all());

        return view('Back.Settings.index', compact('settings'));
    }

    public function create()
    {
        return view('Back.Settings.create');
    }

    public function edit(Setting $setting)
    {
        return view('Back.Settings.edit', compact('setting'));
    }

    public function UpdateAll(Request $request)
    {
        return Setting::updateAll($request);
    }
}

app/Http/Controllers/Back/SportController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Sport;
use App\Http\Controllers\RepoController;
use App\Http\Requests\Back\EditSportRequest;
use App\Http\Requests\Back\CreateSportRequest;
use App\Repository\Contracts\ISportRepository;

class SportController extends RepoController
{
    public function __construct(ISportRepository $repository)
    {
        parent::__construct($repository);
    }

    public function store(CreateSportRequest $request)
    {
        return self::repo()->store($request);
    }

    public function update(EditSportRequest $request, Sport $sport)
    {
        return self::repo()->update($request, $sport);
    }
}

app/Http/Controllers/Back/SubscriptionController.php
<?php

namespace App\Http\Controllers\Back;

use Exception;
use App\Models\Team;
use App\Models\Sport;
use App\Models\User;
use App\Models\Invitation;
use App\Models\Tournament;
use App\Models\Subscription;
use App\Http\Controllers\BASE_CONTROLLER;
use App\Http\Requests\Back\EditSubscriptionRequest;
use App\Http\Requests\Back\CreateSubscriptionRequest;
use App\Facade\Support\CrudMessage;
use App\Facade\Support\Warning;
use App\Exports\TeamsExport;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class SubscriptionController extends BASE_CONTROLLER
{
    public function __construct()
    {
        parent::__construct(Subscription::class);
    }

    public function index()
    {
        $subscriptions = Subscription::with('tournament')
            ->has('tournament')
            ->has('user')
            ->has('sport')
            ->has('team')
            ->has('age')
            ->paginate(10);

        return view('Back.Subscriptions.index', [
            'subscriptions' => $subscriptions,
            'search'        => false
        ]);
    }

    public function create()
    {
        return view('Back.Crud.create', self::formFields());
    }

    public function edit($id)
    {
        return view('Back.Crud.edit', self::formFields('edit', Subscription::findOrFail($id)));
    }

    public function getSportsByTournamentId(Request $request)
    {
        $tournament = Tournament::find($request->tournament_id);

        if(!$tournament) return Warning::tournamentIsNotFound();

        $callback = function($item){
            return ['id' => $item->id,'name' => $item->name];
        };

        $data = $tournament->sports->map($callback);

        return response()->json(['data' => $data->toArray(), 'success' => true]);
    }

    public function getAgesBySportId(Request $request)
    {
        $sport = Sport::find($request->sport_id);

        if(!$sport) return Warning::sportIsNotFound();

        $callback = function($item){
            return ['id' => $item->id,'name' => $item->name];
        };

        $data = $sport->ages->map($callback);

        return response()->json(['data' => $data->toArray(), 'success' => true]);
    }

    public function store(CreateSubscriptionRequest $request)
    {
        DB::beginTransaction();
        try
        {
            $check = Subscription::whereUserId($request->user_id)->whereTournamentId($request->tournament_id)->first();

            if($check)
            {
                if($check->tournament->formatted_start_date->isCurrentDay()) return Warning::userAlreadySubscribeInTournament();

                if($check->tournament->formatted_start_date->isPast()) return Warning::tournamentIsFinished();

                if($check->tournament->formatted_end_date->isPast()) return Warning::tournamentIsFinished();
            }

            $subscriptionData = $request->only(['user_id', 'tournament_id', 'sport_id', 'age_id']);

            $subscription = Subscription::create($subscriptionData);

            if(!is_null($request->invitations_fname[0]) && !is_null($request->invitations_lname[0]) && !is_null($request->invitations_age[0]) && !is_null($request->invitations_birth_date[0]) && !is_null($request->invitations_address[0]))
            {
                $subscription->invitations()->createMany(Subscription::setInvitationData($request));
            }

            $subscription->team()->create(self::getTeamData($request, $subscription));

            DB::commit();

            return CrudMessage::successResponse();
        }
        catch (Exception $e)
        {
            DB::rollBack();
            return CrudMessage::fails($e);
        }
    }

    public function printInvitation(Invitation $invitation)
    {
        return view('Back.Subscriptions.printInvitation', compact('invitation'));
    }

    public function update(EditSubscriptionRequest $request, Subscription $subscription)
    {
        DB::beginTransaction();
        try
        {
            if($subscription->tournament->formatted_start_date->isCurrentDay()) return Warning::tournamentWillStartToday();

            if($subscription->tournament->formatted_start_date->isPast()) return Warning::tournamentIsFinished();

            if($subscription->tournament->formatted_end_date->isPast()) return Warning::tournamentIsFinished();

            DB::table('invitations')->where('subscription_id', $subscription->id)->delete();

            $subscription->invitations()->createMany(Subscription::setInvitationData($request));

            $subscription->team->update(['total' => $subscription->invitations->count() + 1]);

            DB::commit();

            return CrudMessage::successResponse();
        }
        catch (Exception $e)
        {
            DB::rollBack();
            return CrudMessage::fails($e);
        }
    }

    public function teams()
    {
        $data = ['teams' => Team::has('user')->has('sport')->has('subscription')->has('tournament')->paginate(10), 'search' => false];

        return view('Back.Teams.index', $data);
    }

    public function showTeam(Team $team)
    {
        return view('Back.Teams.show', compact('team'));
    }

    public function searchTeam(Request $request)
    {
        if(is_null($request->term)) return redirect()->route('teams.index');

        $data = ['teams' => Team::search($request->term)->paginate(10), 'search' => true];

        return view('Back.Team.index', $data);
    }

    public function teamsPrint()
    {
        $callback = function($query){
            return $query->where('start_date', '>', today());
        };

        $data = ['teams' => Team::whereHas('tournament', $callback)->paginate(10), 'search' => false];

        return view('Back.Teams.print', $data);
    }

    public function teamExport()
    {
        return Excel::download(new TeamsExport, 'teams.xlsx');
    }

    public function formFields($type = 'create', $currentModel = null)
    {
        $data = ['model' => 'subscription', 'users' => User::getInSelectForm(), 'tournaments' => Tournament::getNewTournamentsInSelectForm()];

        $data['sports'] = [];

        $data['ages'] = [];

        $data['addresses'] = User::addresses();

        if($type == 'edit') $data['currentModel'] = $currentModel;

        return $data;
    }

    private static function getTeamData($request, $subscription)
    {
        return [
            'user_id'         => $request->user_id,
            'tournament_id'   => $request->tournament_id,
            'sport_id'        => $request->sport_id,
            'name'            => $request->team_name,
            'total'           => $subscription->invitations->count() + 1,
        ];
    }
}

app/Http/Controllers/Back/TournamentController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Tournament;
use Illuminate\Http\Request;
use App\Http\Controllers\RepoController;
use App\Http\Requests\Back\EditTournamentRequest;
use App\Http\Requests\Back\CreateTournamentRequest;
use App\Http\Requests\Back\EditTournamentSportRequest;
use App\Http\Requests\Back\CreateTournamentSportRequest;
use App\Repository\Contracts\ITournamentRepository;

class TournamentController extends RepoController
{
    public function __construct(ITournamentRepository $repository)
    {
        parent::__construct($repository);
    }

    public function store(CreateTournamentRequest $request)
    {
        return self::repo()->store($request);
    }

    public function update(EditTournamentRequest $request, Tournament $tournament)
    {
        return self::repo()->update($request, $tournament);
    }

    public function sportCreate()
    {
        return self::repo()->sportCreate();
    }

    public function sportStore(CreateTournamentSportRequest $request)
    {
        return self::repo()->sportStore($request);
    }

    public function sportEdit(Tournament $tournament)
    {
        return self::repo()->sportEdit($tournament);
    }

    public function sportUpdate(EditTournamentSportRequest $request, Tournament $tournament)
    {
        return self::repo()->sportUpdate($request, $tournament);
    }

    public function sportRemove(Request $request)
    {
        return self::repo()->sportRemove($request);
    }
}

resources/views/Back/Users/index.blade.php
<x-model-index-page model="user" modelType="male" :collection="$users" columns="7">
    <table class="table table-delete-action-now table-bordered dt-responsive nowrap no-footer dtr-inline text-center f-15" id="users" style="font-size: 16px;">
        <thead>
        <tr>
            <th>#</th>
            <th>@lang('back.form-name')</th>
            <th>@lang('back.form-age')</th>
            <th>@lang('back.form-email')</th>
            <th>@lang('back.form-membership-number')</th>
            <th>@lang('back.form-status')</th>
            <th class="text-center">@lang('back.form-actions')</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $i => $user)
            <tr>
                <td>{{$i+1}}</td>
                <td><a href="{{ route('users.show', $user->id) }}">{!! highlightText($user->full_name, $search) !!}</a></td>
                <td>{!! highlightText($user->age, $search) !!}</td>
                <td>{!! highlightText($user->email, $search) !!}</td>
                <td>{!! highlightText($user->membership_number, $search) !!}</td>
                <td><x-table-switch-status :model="$user"></x-table-switch-status></td>
                <td><x-table-actions modelName="user" :model="$user"></x-table-actions></td>
            </tr>
        @endforeach
        </tbody>
    </table>
</x-model-index-page>

resources/views/Back/Users/print.blade.php
<!doctype html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @include('Back.layouts.partials.styles')
    <title>Document</title>
</head>
<body>
<div class="container">
    <h3>Players</h3>
    <table class="table table-delete-action-now table-bordered text-center dt-responsive nowrap no-footer dtr-inline f-16" id="admins">
        <thead>
        <tr>
            <th>#</th>
            <th>@lang('back.form-name')</th>
            <th>@lang('back.form-age')</th>
            <th>@lang('back.form-email')</th>
            <th>@lang('back.form-membership-number')</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $i => $user)
            <tr>
                <td>{{ $i+1 }}</td>
                <td>{{ $user->full_name ?? trans('back.no-value') }}</td>
                <td>{{ $user->age ?? trans('back.no-value') }}</td>
                <td>{{ $user->email ?? trans('back.no-value') }}</td>
                <td>{{ $user->membership_number ?? trans('back.no-value') }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

</div>
@include('Back.layouts.partials.scripts')
<script>
    $(window).on('load', function(){
        window.print();
    });
</script>
</body>
</html>

resources/views/Back/Users/show.blade.php
<x-model-show-element :title="$user->full_name" model="user" nameSpace="back">
    <div class="col-md-12">
        <div class="card border border-secondary">
            <div class="card-header bg-secondary text-white">@lang('back.users.t-user')</div>
            <div class="card-body">
                <ul class="nav nav-tabs nav-justified">
                    <li class="nav-item">
                        <a href="#user" data-toggle="tab" aria-expanded="false" class="nav-link active">
                            <span class="d-block d-sm-none"><i class="fas fa-home"></i></span>
                            <span class="d-none d-sm-block">@lang('back.users.t-user')</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#subscriptions" data-toggle="tab" aria-expanded="false" class="nav-link">
                            <span class="d-block d-sm-none"><i class="fas fa-cog"></i></span>
                            <span class="d-none d-sm-block">@lang('back.subscriptions.subscriptions') ({{ $user->subscriptions()->has('sport')->count() }})</span>
                        </a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane fade show active" id="user">
                        @include('includes.flash')
                        <div class="row">
                            <div class="col-md-3">
                                <div class="card text-center">
                                    <img class="card-img-top img-fluid" src="{{ Uploaded::default() }}" alt="{{ $user->full_name }}">
                                    <div class="card-body">
                                        <h4 class="card-title">{{ ucwords($user->full_name) }}</h4>

                                        <a href="{{ route('users.edit', $user->id) }}" class="btn btn-block btn-primary">@lang('back.edit')</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="well">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item">
                                            <h4 class="text-muted">@lang('back.form-first-name')</h4>
                                            <h5>{{ $user->fname ?? trans('back.no-value')  }}</h5>
                                        </li>

                                        <li class="list-group-item">
                                            <h4 class="text-muted">@lang('back.form-last-name')</h4>
                                            <h5>{{ $user->lname ?? trans('back.no-value')  }}</h5>
                                        </li>

                                        <li class="list-group-item">
                                            <h4 class="text-muted">@lang('back.form-age')</h4>
                                            <h5>{{ $user->age ?? trans('back.no-value')  }}</h5>
                                        </li>

                                        <li class="list-group-item">
                                            <h4 class="text-muted">@lang('back.form-birth-date')</h4>
                                            <h5>{{ $user->birth_date->format('Y-m-d') ?? trans('back.no-value')  }}</h5>
                                        </li>

                                        <li class="list-group-item">
                                            <h4 class="text-muted">@lang('back.form-membership-number')</h4>
                                            <h5>{{ $user->membership_number ?? trans('back.no-value')  }}</h5>
                                        </li>

                                        <li class="list-group-item">
                                            <h4 class="text-muted">@lang('back.form-status')</h4>
                                            <h5><x-table-switch-status :model="$user"></x-table-switch-status></h5>
                                        </li>

                                        <li class="list-group-item">
                                            <h4 class="text-muted">@lang('back.since')</h4>
                                            <h5>{{ $user->since }}</h5>
                                        </li>

                                        <li class="list-group-item">
                                            <h4 class="text-muted">@lang('back.updated_at')</h4>
                                            <h5>{{ $user->last_update }}</h5>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane fade" id="subscriptions">
                        <div class="table-responsive">
                            <table class="table text-center">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>@lang('back.subscriptions.t-subscription')</th>
                                    <th>@lang('back.tournaments.t-tournament')</th>
                                    <th>@lang('back.sports.t-sport')</th>
                                    <th>@lang('back.ages.t-age')</th>
                                    <th>@lang('back.since')</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($user->subscriptions()->has('sport')->get() as $i => $subscription)
                                    <tr>
                                        <td>{{ $i+1 }}</td>
                                        <td>
                                            <a data-toggle="tooltip" title="@lang('back.subscriptions.t-subscription')" href="{{ route('subscriptions.show', $subscription->id) }}" class="btn btn-dark">
                                                <i class="fa fa-eye"></i> @lang('back.show')
                                            </a>
                                        </td>
                                        <td>
                                            <a data-toggle="tooltip" title="@lang('back.tournaments.t-tournament')" href="{{ route('tournaments.show', $subscription->tournament_id) }}">
                                                {{ ucwords($subscription->tournament->name) }}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ route('sports.show', $subscription->sport_id) }}">
                                                {{ ucwords($subscription->sport->name) }}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ route('ages.show', $subscription->age_id) }}">
                                                {{ ucwords($subscription->age->name) }}
                                            </a>
                                        </td>
                                        <td>{{ $subscription->since }}</td>
                                    </tr>
                                @empty
                                    <x-table-alert-no-value></x-table-alert-no-value>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane fade" id="invitations">
                        invitations
                    </div>
                </div>
            </div>
        </div>

{{--        <div id="view_show_user_send_notification" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">--}}
{{--            <div class="modal-dialog">--}}
{{--                <div class="modal-content">--}}
{{--                    <div class="modal-header">--}}
{{--                        <h4 class="modal-title" id="myModalLabel">@lang('back.send-a-message')</h4>--}}
{{--                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>--}}
{{--                    </div>--}}
{{--                    <div class="modal-body">--}}
{{--                        <form action="{{ route('users.send-notification') }}" method="POST" id="send-notification-form">--}}
{{--                            @csrf--}}
{{--                            <input type="hidden" name="user_id" value="{{ $user->id }}">--}}
{{--                            <div class="form-group">--}}
{{--                                <label for="title">@lang('back.form-title')</label>--}}
{{--                                <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror">--}}
{{--                                @error('title')--}}
{{--                                <span class="invalid-feedback" role="alert">--}}
{{--                                <strong>{{ $message }}</strong>--}}
{{--                            </span>--}}
{{--                                @enderror--}}
{{--                            </div>--}}
{{--                            <div class="form-group">--}}
{{--                                <label for="body">@lang('back.form-body')</label>--}}
{{--                                <textarea name="body" id="body" rows="5" class="form-control @error('body') is-invalid @enderror"></textarea>--}}
{{--                                @error('body')--}}
{{--                                <span class="invalid-feedback" role="alert">--}}
{{--                                <strong>{{ $message }}</strong>--}}
{{--                            </span>--}}
{{--                                @enderror--}}
{{--                            </div>--}}
{{--                        </form>--}}
{{--                    </div>--}}
{{--                    <div class="modal-footer">--}}
{{--                        <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">@lang('back.close')</button>--}}
{{--                        <button type="submit" form="send-notification-form" name="submit" class="btn btn-primary waves-effect waves-light">@lang('back.send')</button>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
    </div>

    <x-slot name="scripts">
        @include('Back.includes.showModelScript', ['class' => 'send-user-message', 'modelId' => 'view_show_user_send_message'])
        @include('Back.includes.redirectAlertScript', ['class' => 'blockUser'])
    </x-slot>
</x-model-show-element>